### ISSUE TITLE
Source of this font ｜ 字体来源

### ISSUE THREAD

**Issue by NightFurySL2001** [CyberFei/D-DIN-PRO#1]
I would like to confirm the source of this font —— is this font modified from D-DIN or is the source of font is modified from commercial fonts?

我想确认字体来源——请问本字体是从D-DIN修改而来，还是从商业字体修改而来？

**Comment by CyberFei** [comment]
D-DIN

**Comment by NightFurySL2001** [comment]
May I ask how did you make the heavier weights since D-DIN only came with two weights? Is there any source files that can be provided to aid further designers (e.g. stroke-separated files)?

想请问您是如何制作多字重呢？D-DIN 仅提供两个字重。请问有源文件可以协助后续设计师吗（比如笔画分离版）？

**Comment by CyberFei** [comment]
本人不是设计师，不同字重是简单通过字体工具「Glyphs」「曲线放样」而来的，没有工程源文件

**Comment by NightFurySL2001** [comment]
好的，感谢解惑。
